# Netlify deployment config for Night Shift Chatroom (夜班聊天室)
[build]
  publish = "."
  command = ""

# Basic headers
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Security headers (optional)
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
